import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="fle flex-col items-center justify-center h-screen w-screen overflow-hidden">
                <h1 className="text-3xl font-extrabold mt-5">New Basic App Created</h1>
                <p>
                    This basic app was generated using <em>create-t3-app</em>
                </p>
                <div>
                    <p>This template includes:</p>
                    <ul>
                        <li>
                            TailwindCSS -{" "}
                            <a href="https://tailwindcss.com/" target="_blank">
                                Read Documentation
                            </a>
                        </li>
                        <li>
                            TypeScript -{" "}
                            <a href="https://www.typescriptlang.org/" target="_blank">
                                Read Documentation
                            </a>
                        </li>
                        <li>
                            Prisma -{" "}
                            <a href="https://www.prisma.io/" target="_blank">
                                Read Documentation
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    );
};

export default Home;
